server.port=8081
spring.application.name=up

spring.datasource.url=jdbc:postgresql://localhost:5432/up_db
spring.datasource.username=postgres
spring.datasource.password=02182531

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=seu_segredo_super_secreto_para_testes_locais